### ISSUE TITLE
rails new　環境構築

### ISSUE THREAD

**Issue by kajimasara-58b** [kajimasara-58b/DreamScope100#7]
- [x] ターミナルでアプリ用ディレクトリにいることを確認する　`$ pwd`

- [x] VScodeでアプリ用ディレクトリを開いてDockerfile.devファイルを作成

```
FROM ruby:3.3.6

ENV LANG C.UTF-8
ENV TZ Asia/Tokyo

# node.jsやらyarnやらなんやらをシステム全体にインストール
RUN apt-get update -qq \
&& apt-get install -y ca-certificates curl gnupg \
&& mkdir -p /etc/apt/keyrings \
&& curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
&& NODE_MAJOR=20 \
&& echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list \
&& wget --quiet -O - /tmp/pubkey.gpg https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
&& echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs yarn vim

# ディレクトリを作成してそれを作業ディレクトリ（Dockerが操作するディレクトリ）に設定
RUN mkdir /myapp
WORKDIR /myapp
RUN gem install bundler

# Dockerfileが存在するディレクトリ内（コンテナの外。今回の場合はRailsのアプリがあるディレクトリ）
# にあるすべてのファイルとサブディレクトリをコンテナ内の/myappにコピー
COPY . /myapp
```

- [x] compose.ymlの作成

```
services:
  db:
    image: postgres
    restart: always
    environment:
      TZ: Asia/Tokyo
      POSTGRES_PASSWORD: password
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d myapp_development -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "bundle install && bundle exec rails db:prepare && rm -f tmp/pids/server.pid && ./bin/dev"
    tty: true
    stdin_open: true
    volumes:
      - .:/myapp
      - bundle_data:/usr/local/bundle:cached
      - node_modules:/myapp/node_modules
    environment:
      TZ: Asia/Tokyo
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
volumes:
  bundle_data:
  postgresql_data:
  node_modules:
```

- [x] Dockerを立ち上げてコンテナビルドする　`$ docker compose build`
- [x] Railsのgemをインストールする　`$ docker compose run --rm web gem install rails -v '7.2.1'`
- [x] Rails new `$ docker compose run --rm web rails new . -d postgresql -j esbuild --css=tailwind`
- [x] ファイルが作成されていればOK　Procfile.devを編集する
```
web: env RUBY_DEBUG_OPEN=true bin/rails server -b 0.0.0.0 -p 3000
js: yarn build --watch
css: yarn build:css --watch
```

- [x] config/database.ymlの修正　Docker環境に合わせてhostとusernameとpasswordを追加
```
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: postgres
  password: password

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  database: myapp_production
  username: myapp
  password: <%= ENV["MYAPP_DATABASE_PASSWORD"] %>
```
- [x] サーバー立ち上げ　`$ docker compose up`
- [x] http://localhost:3000/　にアクセスしてみる
